//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDI_APPICON                     101
#define IDC_TOOLBAR                     101
#define IDR_MAINMENU                    102
#define IDC_STATUSBAR                   102
#define IDI_BROWSEICON                  102
#define IDR_ACCELERATOR                 103
#define IDC_MIPMAPSLIDER                103
#define IDD_ABOUT                       104
#define IDC_INFOTEXT                    104
#define IDB_TOOLBAR                     105
#define IDC_ZOOMLABEL                   105
#define IDR_TOOLBAR                     106
#define IDC_ZOOMSLIDER                  106
#define IDD_PVRFILEINFO                 106
#define IDC_POINT                       106
#define IDC_VSCROLL                     107
#define IDR_BROWSETOOLBAR               107
#define IDC_HSCROLL                     108
#define IDD_VQFSETTINGS                 109
#define IDC_CLIENTAREA                  109
#define IDC_PAN                         110
#define ID_BROWSE_GO                    110
#define IDD_OUTPUTSETTINGS              111
#define IDD_SETGLOBALINDEX              112
#define IDC_ANIM                        112
#define _IDD_VQFSETTINGS_OLD            113
#define IDC_LOG                         113
#define IDI_PVRFILE                     116
#define IDC_COLOURFORMAT_565            1000
#define IDC_COLOURFORMAT_555            1001
#define IDC_COLOURFORMAT_1555           1002
#define IDC_COLOURFORMAT_4444           1003
#define IDC_DITHER                      1004
#define IDC_MIPMAP                      1005
#define IDC_INVERSEALPHA                1006
#define IDC_DOFREQ                      1008
#define IDC_ITERATIONS                  1009
#define IDC_COLORSPACE_RGB              1011
#define IDC_COLORSPACE_YIQ              1012
#define IDC_DEFAULTALPHA                1014
#define IDC_MAXIMUMERROR                1016
#define IDC_WEIGHTING_Y                 1019
#define IDC_WEIGHTING_I                 1020
#define IDC_WEIGHTING_Q                 1021
#define IDC_CODEBOOKSIZE                1024
#define IDC_COLOURFORMAT                1025
#define IDC_MIPMAPS                     1026
#define IDC_TWIDDLE                     1028
#define IDC_GLOBALINDEX                 1029
#define IDC_DISABLEGLOBALINDEX          1030
#define IDC_COLOURMETRIC_RGBA           1031
#define IDC_COLOURMETRIC_EYE            1032
#define IDC_DITHER_NONE                 1033
#define IDC_DITHER_HALF                 1034
#define IDC_DITHER_FULL                 1035
#define IDC_CATEGORY_DESC               1038
#define IDC_KAMUIFORMAT                 1043
#define IDC_FILENAME                    1044
#define IDC_IMAGESIZE                   1045
#define IDC_HIGHFREQTOL                 1049
#define IDC_VERSION                     1050
#define IDC_COPYRIGHT                   1051
#define IDC_MAIL                        1053
#define IDC_VQVERSION                   1054
#define IDC_PAD                         1055
#define IDC_PAINTLIBURL                 1055
#define IDC_FILESIZE                    1056
#define IDC_PALETTEDEPTH                1058
#define ID_FILE_EXIT                    40003
#define ID_HELP_ABOUT                   40004
#define ID_FILE_PROPERTIES              40006
#define ID_TOOLS_GENERATEVQF            40010
#define ID_FILE_IMPORTALPHA             40014
#define ID_VIEW_ZOOMIN                  40015
#define ID_VIEW_ZOOMOUT                 40016
#define ID_VIEW_ZOOMNORMAL              40018
#define ID_EDIT_COPY_IMAGE              40027
#define ID_EDIT_COPY_ALPHA              40028
#define ID_EDIT_COPY_VQFIMAGE           40029
#define ID_EDIT_COPY_VQFALPHA           40030
#define ID_TOOLS_DELETEVQ               40031
#define ID_FILE_SAVEAS                  40033
#define ID_VIEW_STRETCHMIPMAPS          40034
#define ID_TOOLS_DELETEALPHA            40035
#define ID_FILE_EXPORT                  40036
#define ID_VIEW_MIPMAP_IMAGE            40038
#define ID_VIEW_MIPMAP_VQIMAGE          40039
#define ID_VIEW_STRETCHMIPMAP           40040
#define ID_TOOLS_SETGLOBALINDEX         40041
#define ID_TOOLS_DELETEMIPMAPS          40043
#define ID_TOOLS_REGENERATEMIPMAPS      40044
#define ID_TOOLS_REVERSEALPHA           40045
#define ID_FILE_BROWSE                  40046
#define ID_BROWSE_UPONELEVEL            40047
#define ID_BROWSE_NEWFOLDER             40049
#define ID_BROWSE_SWITCHWINDOW          40051
#define ID_BROWSE_REFRESH               40052
#define ID_BROWSE_DESKTOP               40053
#define ID_BROWSE_DOCUMENTS             40054
#define IDC_BROWSEPATH                  40056
#define ID_BROWSE_PROPERTIES            40057
#define ID_BROWSE_OPEN                  40058
#define ID_VIEW_FULLSCREEN              40059
#define ID_VIEW_TILES_VQ                40060
#define ID_VIEW_TILES_IMAGE             40061
#define ID_VIEW_TILES                   40062
#define ID_VIEW_TILES_MIRROR            40065
#define ID_VQ_COMPRESSIONANALYSIS_DIFFERENCEX4 40067
#define ID_VQ_COMPRESSIONANALYSIS_CODEBOOKINDICES 40068
#define ID_EDIT_COPY_REFERENCEIMAGE     40069
#define ID_EDIT_COPY_REFERENCEALPHA     40070
#define ID_VIEW_MIPMAP                  40071
#define ID_VIEW_MIPMAP_REFIMAGE         40073
#define ID_VQ_COMPRESSIONANALYSIS_DIFFERENCE 40074
#define ID_VQ_COMPRESSIONANALYSIS_DELETEREFERENCEIMAGE 40075
#define ID_VQ_COMPRESSIONANALYSIS       40076
#define ID_BROWSE_EXPLORER              40093
#define ID_TOOLS_ENLARGETOPOW2          40095
#define ID_TOOLS_VFLIP                  40096
#define ID_TOOLS_HFLIP                  40097
#define ID_TOOLS_SCALEHALF              40098
#define ID_VIEW_LOG                     40099
#define ID_TOOLS_MAKESQUARE             40100
#define ID_TOOLS_PAGETOMIPMAP           40103
#define ID_TOOLS_MIPMAPSTOPAGE          40104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40105
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
